---
.travis.yml:
  includes:
    - env: PUPPET_GEM_VERSION="~> 5.0" CHECK=build DEPLOY_TO_FORGE=yes
  branches:
    - /^\d/
  deploy: true
  user: MiamiOH
  secure: "UNqfxODE58dUYpTh6hVuNyizmIrdWSRGu0zSkzPxwPOztuX37kUI4TdFZ/j+5LElC/w8h62uf7C0myZg18GzJj/1AVCZesz+knpR78x+2Dmna5t3Shi8nJxqSYko2l4u913D6z0x7v3nKWzw8Pw/zkPM2043Om6ZYd6ESwVbc/58xsydwn4EOvTzmYuH+kZs3yPMTX2m1zHhk28dHRDZ6uIGiw4rtvNIFHTkfkHdkFuG/4N6H6XD1Z6QRN3TKopa7fRpd4GzJQ5W5w2O+AuaxzUr9HJoOBi3kj6qaUwF2cUtC8jC/SShCyYLO98VUz94iSeFDwuTQuQKNofPD0eo1Z3T+utI6QAL3Iep6kGxJKa6OEIosU2bFvsDKprRpS4bUpm4tSg2YfFJHsTl4+ZVaXuDdcGwrPeYo8onbmDDc0DNkCGgQ5yyMcEXBfLTed56/NWZ/6en/le13Hk6FAgBLJbfB0Jkz9FU7X3YUWjq1nKJnWpmEgtawhBnzQSjABTPyJ9dsU/DqF2bifAN7lXG2nCYSJtIpcVni4bfEWoVB/qW1uEjpkzeB55iYVrpWJ2FKeqJZkedcCy0iIUVrpl3s3uo38kVSnrE1P5lhoHKQJsVYbRA6ZOnaV+VjX8jiuXzWuDv9469/nkHEREYfgygRHxZDsoTNRWcJCImukdGq4A="

# .rubocop.yml:
#   include_todos: true

Gemfile:
  required:
    ':development':
      - gem: travis
    ':puppet_lint':
      - gem: puppet-lint-absolute_classname-check
      - gem: puppet-lint-absolute_template_path
      - gem: puppet-lint-alias-check
      - gem: puppet-lint-classes_and_types_beginning_with_digits-check
      - gem: puppet-lint-duplicate_class_parameters-check
      - gem: puppet-lint-empty_string-check
      - gem: puppet-lint-extended
      - gem: puppet-lint-file_ensure-check
      - gem: puppet-lint-file_source_rights-check
      - gem: puppet-lint-leading_zero-check
      - gem: puppet-lint-numericvariable
      - gem: puppet-lint-resource_reference_syntax
      - gem: puppet-lint-security-plugins
      - gem: puppet-lint-spaceship_operator_without_tag-check
      - gem: puppet-lint-strict_indent-check
      - gem: puppet-lint-trailing_comma-check
      - gem: puppet-lint-trailing_newline-check
      - gem: puppet-lint-undef_in_function-check
      - gem: puppet-lint-unquoted_string-check
      - gem: puppet-lint-variable_contains_upcase
      - gem: puppet-lint-version_comparison-check

Rakefile:
  default_disabled_lint_checks:
  - security_package_pinned_version
