---
.travis.yml:
  includes:
    - env: PUPPET_GEM_VERSION="~> 5.0" CHECK=build DEPLOY_TO_FORGE=yes
  branches:
    - /^\d/
  deploy: true
  user: luoy
  secure: "jptZgj4niE+5sXaxboN1KsP+nKg3KviPuijT1BN84vWUftM2QINitquChV+kUJ8rF7v0haOa5+pbSB/d8M1GU569he6bL9xXps+1b5QLNkIO4ocI/T6vfB1ZWEjnkQGjv++XMtm8+UaE4Ip8LeBLDoAie9kXwcjW1MccUe+Bg08lkazanswdC4OCEvnjfRGh0uUjFFjn+8tca6awjgScIX1yXpNKFGJwy1WToZXtJiWyLAgnvgmfPfDpvNzXpq2HZXn4OiaL1WEWMA8coMj3JMUdjvfcG/PDmN/i05HbvTS7Ed98zQwcRtPDYya8NcvFWgfqRy/c+vg68bHvED/PogwzcAX0AldCfRTXntu5xKns4Kq07teqGNG17EC2yL3iCvki4BcGY2T7uEZmZxxSd+lg8L4f2GG5xo0IzbMnLvdnuHkE4Lc87rGa+4kd/zkkYMk7Q3SZyEnlNStZHvzDGgohDmEoob4qEH88iiXpcM8xRmTHhWJ6k4CVobJK75clc0hkL+32Y6myUgitNWXNYFqBHg+AETakLMjoL9AIYFLZFT7tmSPYEh5oE9euY5Vb+9iIQWX1dzusSUpMKqpiYkCsk846RlzW6V2S5sLgzPnKryjNSpTo0xIvLtibGmJQegB6t0iyoz8lm/ZJYfNiUMK/EDcpAnL9a5AG5xVomrc="

# .rubocop.yml:
#   include_todos: true

Gemfile:
  required:
    ':development':
      - gem: travis
    ':puppet_lint':
      - gem: puppet-lint-absolute_classname-check
      - gem: puppet-lint-absolute_template_path
      - gem: puppet-lint-alias-check
      - gem: puppet-lint-classes_and_types_beginning_with_digits-check
      - gem: puppet-lint-duplicate_class_parameters-check
      - gem: puppet-lint-empty_string-check
      - gem: puppet-lint-extended
      - gem: puppet-lint-file_ensure-check
      - gem: puppet-lint-file_source_rights-check
      - gem: puppet-lint-leading_zero-check
      - gem: puppet-lint-numericvariable
      - gem: puppet-lint-resource_reference_syntax
      - gem: puppet-lint-security-plugins
      - gem: puppet-lint-spaceship_operator_without_tag-check
      - gem: puppet-lint-strict_indent-check
      - gem: puppet-lint-trailing_comma-check
      - gem: puppet-lint-trailing_newline-check
      - gem: puppet-lint-undef_in_function-check
      - gem: puppet-lint-unquoted_string-check
      - gem: puppet-lint-variable_contains_upcase
      - gem: puppet-lint-version_comparison-check
