---
sudo: false
dist: trusty
language: ruby
cache: bundler
before_install:
  - bundle -v
  - rm -f Gemfile.lock
  - gem update --system
  - gem --version
  - bundle -v
script:
  - 'bundle exec rake $CHECK'
bundler_args: --without system_tests
rvm:
  - 2.5.0
env:
  global:
    - BEAKER_PUPPET_COLLECTION=puppet6 PUPPET_GEM_VERSION="~> 6.0"
matrix:
  fast_finish: true
  include:
    -
      env: CHECK="syntax lint metadata_lint check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop"
    -
      env: CHECK=parallel_spec
    -
      env: PUPPET_GEM_VERSION="~> 5.0" CHECK=parallel_spec
      rvm: 2.4.4
    -
      env: PUPPET_GEM_VERSION="~> 4.0" CHECK=parallel_spec
      rvm: 2.1.9
    -
      env: PUPPET_GEM_VERSION="~> 5.0" CHECK=build DEPLOY_TO_FORGE=yes
branches:
  only:
    - master
    - /^v\d/
    - /^\d/
notifications:
  email: false
deploy:
  provider: puppetforge
  user: luoy
  password:
    secure: "jptZgj4niE+5sXaxboN1KsP+nKg3KviPuijT1BN84vWUftM2QINitquChV+kUJ8rF7v0haOa5+pbSB/d8M1GU569he6bL9xXps+1b5QLNkIO4ocI/T6vfB1ZWEjnkQGjv++XMtm8+UaE4Ip8LeBLDoAie9kXwcjW1MccUe+Bg08lkazanswdC4OCEvnjfRGh0uUjFFjn+8tca6awjgScIX1yXpNKFGJwy1WToZXtJiWyLAgnvgmfPfDpvNzXpq2HZXn4OiaL1WEWMA8coMj3JMUdjvfcG/PDmN/i05HbvTS7Ed98zQwcRtPDYya8NcvFWgfqRy/c+vg68bHvED/PogwzcAX0AldCfRTXntu5xKns4Kq07teqGNG17EC2yL3iCvki4BcGY2T7uEZmZxxSd+lg8L4f2GG5xo0IzbMnLvdnuHkE4Lc87rGa+4kd/zkkYMk7Q3SZyEnlNStZHvzDGgohDmEoob4qEH88iiXpcM8xRmTHhWJ6k4CVobJK75clc0hkL+32Y6myUgitNWXNYFqBHg+AETakLMjoL9AIYFLZFT7tmSPYEh5oE9euY5Vb+9iIQWX1dzusSUpMKqpiYkCsk846RlzW6V2S5sLgzPnKryjNSpTo0xIvLtibGmJQegB6t0iyoz8lm/ZJYfNiUMK/EDcpAnL9a5AG5xVomrc="
  on:
    tags: true
    all_branches: true
    condition: "$DEPLOY_TO_FORGE = yes"
